### ISSUE TITLE
needs to redo all connection in map each time a character doesnt move at the same speed on grass/dirt

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#10]
Okay here's the problem, lets say you have 2 characters that moves on a map of grass, dirt etc
you want the first character to be really fast on grass and slow and dirt (but the second character is the opposite for instance)
you're only way right now is:
- to update all the cost of all the connections each time you change player (I don't know how extensive it would be, i'll need to run some test) 
or 
-having one map for each player (which I'm pretty sure can quickly become expensive)

Lets discuss this :
It would be nice to be able to update only connections that needs updating, 
->Is it really a problem?
if rewriting all connection on the map each time isnt that costly, we can abort this issue
->One solution that comes to mind
 having cost being flags (or still float like an enum with {Flags(int32),simple_cost(float32)} which would be read like now if it is a simple_cost, but would look up in a (optional? ) provided dictionary to get the cost (specific to the dico, hence to the character) with the value of the enum as key 

PS: once it is discussed, I can work on this (it would be my first rust project so might take some time :p )

**Comment by MatejSloboda** [comment]
I was thinking of something similar. My solution is to store "terrain type" (basically an enum) for each point. User may optionally provide a dictionary with weights for terrain types (absent entries are assumed to have default weight 1.0 ).
When dijkstra map is recalculated, it multiplies the cost of each connection with the average of the weights of the connected points.

Simple example: The map is a straight corridor. points are marked by their terrain types. Numbers in brackets are default connection costs.
...->dirt<-(1.41)->dirt<-(1.0)->dirt<-(1.0)->road<-(1.0)->road<-...
User provides a weight dictionary {dirt: 2.0, road: 1.0}. Now when dijkstra map is recalculated the effective costs are:
...->dirt<-(2.82)->dirt<-(2.0)->dirt<-(1.5)->road<-(1.0)->road<-...
Notice the 1.5 when the map transitions between dirt and road. It simulates the fact that the traveler spends half the time on dirt and half on road, when he transitions between the points.

Alternatively, we might be storing the "terrain type" per connection. In that case, the "terrain type" would be more appropriately named as "terrain transition". However, this would be impractical, because the user would have to provide weights for each relevant terrain transition.
It also doesn't provide any additional functionality either, because the same effects can be replicated with the above-mentioned method + splitting connections in half and adding "transition terrain" points in between.

I'm already working on this terrain weights feature and am near completion. I will push it later this day.

**Comment by astrale-sharp** [comment]
Okay, very nice!
