### ISSUE TITLE
initialize_as_grid bitmaps should defaut to all true

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#22]
there is a lot of case where you want your entire grid, plus you can always disable points later if you need too, I think it would be of better usability :)

**Comment by astrale-sharp** [comment]
even though its really easy to do in gdscript !

**Comment by astrale-sharp** [comment]
note that the IDijkstraMap Node work around with that so it not really a problem

**Comment by MatejSloboda** [comment]
The initialize as grid need more thought in general now that terrain types were added. Perhaps a better option would be to receive either a bitmap or a vector2. If vector2 is provided, the grid is initialized as fully walkable. The bitmap would behave as is.

**Comment by astrale-sharp** [comment]
I'm not sure I understand ^^'
specifically "the grid is initialized as fully walkable."
and  "The bitmap would behave as is."
are the part of the statement my brain cant compile
specifically "walkable" Im not sure what that means in that context
"behave as is" Im not sure how it behaves now so I cant infer how it would behave then ;)

**Comment by MatejSloboda** [comment]
In the current version, the method loops over the bitmap and adds a point only if the bitmap is true at those coordinates. The points that are added are "walkable" or "passable". If the bitmap is false at given position, the point is considered "impassable" (ie. a wall) and point isn't added.
Bitmaps in godot are initialized to false by default. I wish to keep it that way. Instead, I want to allow the first argument to be a vector2. If a vector2 is provided instead of Bitmap, the grid is initialized with all points (as if a bitmap with all true values was provided).

Anyway, I'm not happy with how the method works currently. I think I will add additional wrappers around it for specific types of grid (such as hex, orthogonal, 8-way, isometric, etc. ).

Or even better, expose some enum to godot, that could be used as an argument. Unfortunately, I wasn't able to figure out how to do that. It would also help with the "recalculate" method, because at the moment, the optional arguments are identified by strings. It is easy to make a typo.

**Comment by astrale-sharp** [comment]
yea I one hundred % totally agree on the enum, I'll go ask on the godot discord and post here if I find something or get an answer !

**Comment by astrale-sharp** [comment]
Im being told its not possible currently ..

**Comment by MatejSloboda** [comment]
I suspected as much.
Anyway, I've discovered that Rust's cargo can auto-generate documentation. I modified the source file a little to support this. You can run `cargo doc --no-deps` and it will generate the documentation as html and put it into /target/doc/ directory.

**Comment by astrale-sharp** [comment]
it was because it missed a '/' that the documentation didn't build ! I was wondering (this is my first rust project after all ;) )

**Comment by MatejSloboda** [comment]
Mine too... I was wondering why those "/// comments" in various rust source files online match exactly with their documentation.

**Comment by astrale-sharp** [comment]
lets decide how we change that method and then I'll deal with it, in the meantime I'll fix the demo.tscn
I propose :
* an optional argument "Style" default would default to "None" or orthogonal
* the relative_connections become optional and default to {} set
* initial_offset defaults to 0
* more style idea:
-you mentioned hexagonal but I'm unsure what it means exactly
- any more idea?
```

    pub fn initialize_as_grid(
        &mut self,
        mut _owner: gdnative::Node,
        bitmap: gdnative::BitMap,
------> style : string
        relative_connections_in: gdnative::Dictionary,
        initial_offset: i32,
    )-> gdnative::Dictionary

```

**Comment by MatejSloboda** [comment]
Unfortunately different types of grids and movement types do not have widely agreed-upon names. I think we need to simplify it by splitting it into different functions:
```
add_square_grid(initial_offset: int, bounds: Rect2D , orthogonal_cost: float =1.0, diagonal_cost: float =INF, terrain: int=-1)
add_isometric_grid(initial_offset: int, bounds: Rect2D , orthogonal_cost: float =1.0, diagonal_cost: float =INF, terrain: int=-1)
add_hexagonal_grid(initial_offset: int, bounds: Rect2D , orthogonal_cost: float, terrain: int=-1)
```
They will be much easier to implement and much more clear about what the parameters mean.

**Comment by astrale-sharp** [comment]
okay I'll close this and open a new issue
