### ISSUE TITLE
unit test dont pass

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#29]
you can run all test by launching Gut.tscn scene, as you will see 9 of them fails meaning :
A -> I dont understand the API
B -> the API doesnt work as it should

I'll let you judge seeing the code, I might be the problem but Im not sure (plus I love unit test)

**Comment by MatejSloboda** [comment]
`connect_points()` method returns true if connection already existed (ie. if you are trying to connect points that are already connected). It returns false, if the points are invalid or if the connection between them didn't exist. Or at least that's how I originally wrote it. 
It seems you assumed that the return value indicates whether connection was added successfully. In retrospect, I have to agree, that would make more sense.

The test after that fails because 1 is connected to 2 but not vice versa. When you recalculate map for point 1, it is inaccessible from anywhere but itself. Note, that by default recalculate treats it as a target - paths follow connections from sources (all points in the map) to targets.
It also has cost 0.0 because it's a target - your path has length and cost 0 when you are already at the target.

**Comment by MatejSloboda** [comment]
Basically, you assumed that the calculated paths lead in the opposite direction. I can rewrite the test to succeed if you wish.

**Comment by MatejSloboda** [comment]
I've remembered why I implemented connect_points the way I did. There is no set_connection_weight method. The connect_points method is used both for connecting new points and updating cost of existing connections. The output indicates whether you are updating existing connection or not.

**Comment by astrale-sharp** [comment]
Oh no don't worry I'll rewrite them ! I needs this to get comfy with the API ! ;)

Oh okay! very interesting, I didn't even thought of that ( never had the need so ) I didnt understood what 'source' and 'target' meant !
si if you pass 'reversed'=true, then it acts as a source, is that right?

**Comment by MatejSloboda** [comment]
Yes, that is correct. Perhaps we should make some changes the the API to make it clear. For example, rename the "reversed" option to "target as source".
To clarify, the algorithm works exactly the same in both cases. "reversed" just switches direction of the connections it takes into account. 
Example: let's say the graph is 1->2.
recalculate(1,{"reversed":false}) will yield a map, where 1 points to itself (because it's the target) and 2 is inaccessible (because there are no connections from 2 to 1).
recalculate(1,{"reversed":true}) will yield a map where 2 points to 1, because point 2 can be accessed from 1.

**Comment by astrale-sharp** [comment]
thank you I understand now !
hmm, its an open discussion "target as source" seems a little confusing to me, because not "target as source" => "target as target"?
which leads to what is "as source", "as target" and so on ^^'
I would consider "id as source" or just "source" with id implicit, what do you think?

**Comment by MatejSloboda** [comment]
I think we can safely assume that whoever is using DijkstraMap is probably familiar with what it is. The rest of the API is mostly self-explanatory. The `recalculate()` method is the only one that is somewhat cryptic. It doesn't really say anywhere (except documentation) that the first input is treated as target by default. If I'd open the example project and saw `dijkstra_map.recalculate(source,{"source":true})` I would have no idea what it means.
My best idea so far is to reverse the default behavior (ie. input would be treated as source by default) and name the parameter "input is destination". It is much more clear what the parameter means, because "source" and even "target" are very ambiguous in this context.

**Comment by astrale-sharp** [comment]
> My best idea so far is to reverse the default behavior (ie. input would be treated as source by default) and name the parameter "input is destination". It is much more clear what the parameter means, because "source" and even "target" are very ambiguous in this context.
> 
I agree with this,  it seems right


> If I'd open the example project and saw dijkstra_map.recalculate(source,{"source":true}) I would have no idea what it means.
>
Its the first time I heard about Dijkstra so I think its smarter to listen to what you say here
