### ISSUE TITLE
connect_points silently fails if cost is int instead of float

### ISSUE THREAD

**Issue by astrale-sharp** [MatejSloboda/Dijkstra_map_for_Godot#3]
Hey,
if cost is of type  int, connect_points returns Null and doesnt work

I intend to try to fix this myself and send you a PR but right now I'm doing some more testing ;)

**Comment by MatejSloboda** [comment]
It seems to work as expected. Rust is statically typed. It raises an error when you pass wrong number of arguments or arguments of different type. In this case, passing int instead of float raises error. I agree that passing int should just convert it to float. I have to look deeper into the API to figure this one out.

**Comment by astrale-sharp** [comment]
One work around I have come with is to have an IDjkstraMap node in gdscript that have the same function signature as the rust API, GDscript should then correctly use the int as a float ;)
not ready or tested yet but i can PR when it is ;)
