### ISSUE TITLE
should ID-to-position dictionary be build into the Dijkstra Map?

### ISSUE THREAD

**Issue by MatejSloboda** [MatejSloboda/Dijkstra_map_for_Godot#54]
I'm debating whether we should add it in for convenience. I also added A* pathfinder into the project and it needs the position for the heuristic to work. At the moment, user has to provide the ID-to-position manually.
Position to ID would be harder to add, since multiple points may share the same position.

**Comment by astrale-sharp** [comment]
I dont think so, I would argue when you use gdnative, you're never quite sure its working since it wont crash no matter what happens (if you dont have the terminal open you might not event see the errors)
plus I'm not sure you quite have the same debug option from the editor
so having logic in gdnative is okay but datastructures seems a little risky
+ its easy to provide so manually
+ They can always use Astar or Astar2D (which are implemented in C++ it might even run a little faster)
